apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: service-test
  template:
    metadata:
      labels:
        app: service-test
    spec:
      containers:
      - name: service-test
        image: rawkode
        imagePullPolicy: IfNotPresent
        resources: {}
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: rawkode
spec:
  type: NodePort
  selector:
    app: service-test
  ports:
  - port: 4000
